spring.application.name=Spring_jpa_template


# ===== DB設定 =====
spring.datasource.url=jdbc:mysql://localhost:3306/sample_db
spring.datasource.username=root
spring.datasource.password=password
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ===== JPA設定 =====
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

# ===== 文字コード =====
# UTF-8固定になる
server.servlet.encoding.charset=UTF-8  

server.servlet.encoding.enabled=true
server.servlet.encoding.force=true